### ISSUE TITLE
Support more OpenSSL types?

### ISSUE THREAD

**Issue by richsalz** [njones/pbr#1]
Pretty cool and elegant.  BTW, you can find more PEM types in include/openssl/pem.h :)

**Comment by njones** [comment]
Yes, that sounds great. I was having trouble creating and displaying the different block types. If you have some that you need. 

I've just added a generate.sh file to the /test directory to keep track of how to create and display the different block types in OpenSSL.

Feel free to generate a pull request to add to the /test directory, updating the generate.sh file.

**Comment by richsalz** [comment]
If you sent email to openssl-users asking for a sample of each, I betcha folks would volunteer. :)  (https://mta.openssl.org for mailing list info)
